name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: java-runtime
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
        
    - name: Build 
      run: chmod +x gradlew; ./gradlew build
    
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: zipfile
        path: java-runtime/build/distributions/hello.zip
        if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: java-runtime
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: zipfile
        path: java-runtime/build/distributions/
 
    - uses: Teakowa/setup-serverless@main
      with:
        provider: aws
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY}}
    
    - name: Deploy
      run: serverless deploy --stage main --verbose
