name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: java-runtime

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
      
    - name: Build 
      run: chmod +x gradlew; ./gradlew build
    
    - name: Deploy
      uses: serverless/github-action@v1.53.0
      with:
        args: -c "serverless deploy --stage main --verbose"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
        SLS_DEBUG: 1
